name: Sync Gitee to GitHub
on:
  push:
    branches: [ main, master, '*' ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: recursive
          # token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: view Project
        run: |
          ls -lah xxl-job/
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'
          cache-dependency-path: |
            pom.xml
            **/pom.xml
            **/.mvn/wrapper/maven-wrapper.properties
            **/.mvn/extensions.xml
      - name: Build with Maven
        run: |
          #  mvn -f pom.xml clean package -pl module-a -am [-pl module-a：构建指定模块 -am：同时构建依赖模块]  -Pprod -DskipTests [多模块-pl common,service-a,service-b】
          # 使用模块路径 mvn clean packag -pl ./common,./service-a,./service-b
          # 排除模块 mvn package -pl '!web,!test'
          mvn -f xxl-job/pom.xml clean package -pl ./xxl-job-admin,./xxl-job-executor-samples/xxl-job-executor-sample-springboot -am -Dmaven.test.skip=true
      - name: view Build Project
        run: |
          ls -alh xxl-job/xxl-job-admin/target/*.jar
          ls -alh xxl-job/xxl-job-executor-samples/xxl-job-executor-sample-springboot/target/*.jar
      # --platform=linux/arm64 ARM64（M1 / ARM服务器）  linux/amd64  【# --build-arg ROOT_PASSWORD=1qaz@WSX \】
      #- name: Prepare docker context
      #  run: |
      #    cp \
      #    $(find xxl-job/xxl-job-admin/target \
      #    -name "*.jar" \
      #    ! -name "*sources.jar" \
      #    ! -name "*javadoc.jar") \
      #    docker/app.jar
      - name: Prepare application jars
        shell: bash
        run: |
          set -euo pipefail
          index=1
          find . -maxdepth 4 -type f -name "*.jar" \
            ! -name "*-sources*.jar" \
            ! -name "*-javadoc*.jar" \
            | while IFS= read -r jar
          do
            if jar tf "$jar" | grep -q "^BOOT-INF/"; then
              filename=$(basename "$jar")
              echo "Found Spring Boot jar: $jar"
              cp "$jar" "./docker/appp$index/$filename"
              echo "Copied: ./apps/app$index/$filename"
              index=$((index+1))
            fi
          done
      - name: Build
        run: |
          ls -alh ./apps/
          export PROJECT_DIR=$GITHUB_WORKSPACE
          docker build --build-arg HOST_WORK_DIR=$PROJECT_DIR \
            --build-arg MYSQL_VERSION=9.7.1 \
            --build-arg GLIBC_VER=2.28 \
            -t "${{ github.repository }}:latest" \
            -f $PROJECT_DIR/Dockerfile-supervisor \
            $PROJECT_DIR
          docker images
