name: Sync Gitee to GitHub
on:
  push:
    branches: [ main, master, '*' ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      # --platform=linux/arm64 ARM64（M1 / ARM服务器）  linux/amd64
      - name: Build
        run: |
          export PROJECT_DIR=$GITHUB_WORKSPACE
          docker build --build-arg HOST_WORK_DIR=$PROJECT_DIR \
            --build-arg MYSQL_VERSION=9.7.1 \
            --build-arg GLIBC_VER=2.28 \
            -t "${{ github.repository }}:test" \
            -f $PROJECT_DIR/Dockerfile-supervisor \
            $PROJECT_DIR
          docker images
