name: Sync Gitee to GitHub
on:
  push:
    branches: [ main, master, '*' ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'
          cache-dependency-path: |
            pom.xml
            **/pom.xml
            **/.mvn/wrapper/maven-wrapper.properties
            **/.mvn/extensions.xml
      - name: Build with Maven
        run: |
          mvn package -Dmaven.test.skip=true
          ls -alh
      # --platform=linux/arm64 ARM64（M1 / ARM服务器）  linux/amd64  【# --build-arg ROOT_PASSWORD=1qaz@WSX \】
      - name: Build
        run: |
          export PROJECT_DIR=$GITHUB_WORKSPACE
          docker build --build-arg HOST_WORK_DIR=$PROJECT_DIR \
            --build-arg MYSQL_VERSION=9.7.1 \
            --build-arg GLIBC_VER=2.28 \
            -t "${{ github.repository }}:latest" \
            -f $PROJECT_DIR/Dockerfile-supervisor \
            $PROJECT_DIR
          docker images
